In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn .preprocessing import StandardScaler
from sklearn.metrics import r2_score,mean_squared_error

In [50]:
df = pd.read_csv("Housing.csv")
df.shape

(545, 13)

In [51]:
df.head()
df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [7]:
encoder = LabelEncoder()

In [8]:
en_mainroad = encoder.fit_transform(df.loc[:,['mainroad']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
en_guestroom = encoder.fit_transform(df.loc[:,['guestroom']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
en_basement = encoder.fit_transform(df.loc[:,['basement']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [11]:
en_hotwaterheating = encoder.fit_transform(df.loc[:,['hotwaterheating']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [12]:
en_airconditioning = encoder.fit_transform(df.loc[:,['airconditioning']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [13]:
en_prefarea = encoder.fit_transform(df.loc[:,['prefarea']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [14]:
en_furnishingstatus = encoder.fit_transform(df.loc[:,['furnishingstatus']])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
df.loc[:,['en_mainroad']] = en_mainroad

In [16]:
df.loc[:,['en_guestroom']] = en_guestroom

In [17]:
df.loc[:,['en_basement']] = en_basement

In [18]:
df.loc[:,['en_hotwaterheating']] = en_hotwaterheating

In [19]:
df.loc[:,['en_airconditioning']] = en_airconditioning

In [20]:
df.loc[:,['en_prefarea']] = en_prefarea

In [21]:
df.loc[:,['en_furnishingstatus']] = en_furnishingstatus

In [22]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,en_mainroad,en_guestroom,en_basement,en_hotwaterheating,en_airconditioning,en_prefarea,en_furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1,0,0,0,1,1,0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1,0,0,0,1,0,0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1,0,1,0,0,1,1
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1,0,1,0,1,1,0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1,1,1,0,1,0,0

In [23]:
df.loc[:,'en_guestroom'].value_counts()

en_guestroom
0    448
1     97
Name: count, dtype: int64

In [24]:
df.loc[:,'guestroom'].value_counts()

guestroom
no     448
yes     97
Name: count, dtype: int64

In [25]:
df.drop(['mainroad','guestroom','basement','hotwaterheating','airconditioning','prefarea','furnishingstatus'], axis= 1,inplace=True)

In [26]:
df

,price,area,bedrooms,bathrooms,stories,parking,en_mainroad,en_guestroom,en_basement,en_hotwaterheating,en_airconditioning,en_prefarea,en_furnishingstatus
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,2,1,0,1,0,0,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,0,1,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,0,1,0,0,0,0,0,2

In [27]:
scalar = StandardScaler()

In [28]:
s_area = scalar.fit_transform(df.iloc[:,1:2])

In [29]:
df.insert(1,column='s_area',value=s_area)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                545 non-null    int64
 1   s_area               545 non-null    float64
 2   area                 545 non-null    int64
 3   bedrooms             545 non-null    int64
 4   bathrooms            545 non-null    int64
 5   stories              545 non-null    int64
 6   parking              545 non-null    int64
 7   en_mainroad          545 non-null    int32
 8   en_guestroom         545 non-null    int32
 9   en_basement          545 non-null    int32
 10  en_hotwaterheating   545 non-null    int32
 11  en_airconditioning   545 non-null    int32
 12  en_prefarea          545 non-null    int32
 13  en_furnishingstatus  545 non-null    int32
dtypes: float64(1), int32(7), int64(6)
memory usage: 44.8 KB

In [31]:
# x,y = df.iloc[:,2:],df.iloc[:,1:2]

In [32]:
x,y = df.iloc[:,2:],df.iloc[:,0:1]

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=50)

In [34]:
y

        price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [35]:
x_test

,area,bedrooms,bathrooms,stories,parking,en_mainroad,en_guestroom,en_basement,en_hotwaterheating,en_airconditioning,en_prefarea,en_furnishingstatus
333,3000,3,1,2,0,1,0,0,0,0,0,1
37,9000,4,2,4,2,1,0,0,0,1,0,0
396,3640,2,1,1,1,1,0,0,0,0,0,1
494,6800,2,1,1,0,1,0,0,0,0,0,2
536,3420,5,1,2,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
269,3900,3,1,2,0,1,0,0,0,0,0,2
472,3630,4,1,2,3,1,0,0,0,0,0,1
521,3635,2,1,1,0,0,0,0,0,0,0,2
145,5000,3,1,4,0,1,0,0,0,0,0,0
244,5320,3,1,2,0,1,1,1,0,0,1,1

In [36]:
model = LinearRegression()

In [37]:
model.fit(x_train,y_train)

LinearRegression()

In [38]:
y_pred = model.predict(x_test)

In [39]:
y_test

       price
333  3920000
37   7980000
396  3500000
494  2730000
536  1960000
..       ...
269  4375000
472  3010000
521  2408000
145  5600000
244  4550000

[109 rows x 1 columns]

In [40]:
y_pred

array([[ 3358068.53544935],
       [ 8464191.99499452],
       [ 3205429.62578452],
       [ 3436225.70027218],
       [ 2972459.97655173],
       [ 7375555.83990435],
       [ 6426149.39050664],
       [ 4460869.40645302],
       [ 3845075.6553084 ],
       [ 4542704.51165384],
       [ 2479695.2655871 ],
       [ 4012051.85203732],
       [ 3728004.14128508],
       [ 5191969.36010061],
       [ 3851534.17868486],
       [ 3634498.49587972],
       [ 4891753.13599567],
       [ 4017390.97506914],
       [ 6255633.83606134],
       [ 6596313.36949275],
       [ 5220009.43966466],
       [ 6257876.38468613],
       [ 4403616.1605166 ],
       [ 3518943.92736549],
       [ 4996035.11953328],
       [ 2693941.34633538],
       [ 4890504.42832327],
       [ 3093629.39198836],
       [ 5843345.10526967],
       [ 2876011.09352742],
       [ 3954949.01527097],
       [ 4504875.19900095],
       [ 3923068.04639501],
       [ 5160019.1352634 ],
       [ 6328907.80195805],
       [ 2715873.82029956],
       [ 2897122.39938055],
       [ 6393742.78419428],
       [ 4932432.64533224],
       [ 4492205.2832729 ],
       [ 3705945.44389484],
       [ 2307340.64568853],
       [ 3613287.46778586],
       [ 7334268.9502263 ],
       [ 3344675.57369223],
       [ 4893387.85874296],
       [ 3590684.32584608],
       [ 6263315.50324676],
       [ 4053324.67068886],
       [ 5315848.10478551],
       [ 5195646.4727531 ],
       [ 4328752.94830661],
       [ 6061504.64930349],
       [ 3988680.4552249 ],
       [ 4938267.52009359],
       [ 5388617.46982059],
       [ 6844029.00327253],
       [ 6572240.49936998],
       [ 5695471.58982668],
       [ 4375359.74228289],
       [ 7238177.31964879],
       [ 6503903.44724432],
       [ 2610842.8463349 ],
       [ 6934723.36137134],
       [ 3862903.97779152],
       [ 5731959.38844875],
       [ 2638800.95467918],
       [ 3478636.28346096],
       [ 5140189.42878262],
       [ 6394334.41814929],
       [ 5720044.27691072],
       [ 7568823.11441005],
       [ 5568926.47000035],
       [ 3122282.41859748],
       [ 2767236.09071782],
       [ 3333034.31393004],
       [ 3589157.06073157],
       [ 6456353.41139852],
       [ 2829429.7860835 ],
       [ 2613609.5771324 ],
       [10626269.39474091],
       [ 2844533.4362729 ],
       [ 8108900.65168225],
       [ 5446973.15802317],
       [ 3042826.90432074],
       [ 5183468.79875849],
       [ 4619154.22579603],
       [ 2777546.84193689],
       [ 2993286.74479338],
       [ 7321719.75593086],
       [ 3629723.89755195],
       [ 5248768.63169318],
       [ 2646931.04381567],
       [ 7341506.56040592],
       [ 6736631.54327265],
       [ 2866975.89900955],
       [ 7441581.73607444],
       [ 3899540.47824397],
       [ 5190749.46776909],
       [ 3915277.23203743],
       [ 4484047.92265079],
       [ 7330914.20924525],
       [ 6522195.57249088],
       [ 3823386.77595548],
       [ 3362979.67805836],
       [ 4541435.37598348],
       [ 2156247.83177853],
       [ 4974725.22217114],
       [ 5093844.67528806]])

In [41]:
r2_score(y_test,y_pred)

0.7624579467323477

In [42]:
mean_squared_error(y_test,y_pred)

807848838640.2025

In [43]:
import joblib

In [44]:
joblib.dump(model,'HousePrice_pridiction.pkl')

['HousePrice_pridiction.pkl']

In [45]:
m = joblib.load('HousePrice_pridiction.pkl')

In [46]:
import numpy as np
a = np.array([1.777,2,1,2,0,1,1,0,1,0,0,0])
a

array([1.777, 2.   , 1.   , 2.   , 0.   , 1.   , 1.   , 0.   , 1.   ,
       0.   , 0.   , 0.   ])

In [47]:
m.predict([a])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[3861139.43820334]])

In [48]:
model.predict([a])

C:\Users\sanje\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[3861139.43820334]])